// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '* @Author': Yico
    '* @Date': 2021-11-05 16:56:12
    '* @Description':  */
    '* @Email': 2604482363@qq.com
    ElButton: typeof import('element-plus/es')['ElButton']
  }
}

export { }
